# Generated by Django 3.2.13 on 2022-06-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0003_auto_20220611_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrecipientinfomodel',
            options={'verbose_name': 'recipient info', 'verbose_name_plural': 'Recipients info'},
        ),
        migrations.RemoveField(
            model_name='customerrecipientinfomodel',
            name='parent_sender',
        ),
    ]
