# Generated by Django 3.2.13 on 2022-06-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0005_auto_20220613_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxordermodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
