# Generated by Django 3.2.13 on 2022-06-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0006_alter_boxordermodel_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='ordering_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
