# Generated by Django 3.2.13 on 2022-06-13 07:53

import crm_employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0007_auto_20220613_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='inside_track_number',
            field=models.CharField(default=crm_employees.models.inside_track_number_generator, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='intarnational_track_number',
            field=models.CharField(default=crm_employees.models.intarnationsal_track_number_generator, max_length=13, unique=True),
        ),
    ]
