# Generated by Django 3.2.13 on 2022-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0010_deliveryparcelmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxordermodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
