# Generated by Django 3.2.13 on 2022-06-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0012_auto_20220617_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxordermodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New order'), ('DEL', 'Delivered')], default='NEW', max_length=3),
        ),
    ]
