# Generated by Django 3.2.13 on 2022-06-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0013_alter_boxordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxordermodel',
            name='ordering_date',
            field=models.DateTimeField(),
        ),
    ]
