# Generated by Django 3.2.13 on 2022-06-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0015_alter_boxordermodel_ordering_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxordermodel',
            name='ordering_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
