# Generated by Django 3.2.13 on 2022-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0016_alter_boxordermodel_ordering_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTariffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'delivery tariff',
                'verbose_name_plural': 'Delivery tariffs',
            },
        ),
        migrations.AddField(
            model_name='boxordermodel',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
