# Generated by Django 3.2.13 on 2022-06-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0017_auto_20220620_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='price',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='crm_employees.deliverytariffmodel'),
            preserve_default=False,
        ),
    ]
