# Generated by Django 3.2.13 on 2022-06-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0019_boxtariffmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxtariffmodel',
            options={'verbose_name': 'box tariff', 'verbose_name_plural': 'Tariff: Boxes'},
        ),
        migrations.AlterModelOptions(
            name='deliveryparcelmodel',
            options={'verbose_name': 'deliver order', 'verbose_name_plural': 'Tariff: Delivery'},
        ),
    ]
