# Generated by Django 3.2.13 on 2022-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0021_alter_boxtariffmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierTariffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'courier tariff',
                'verbose_name_plural': 'Tariff: Courier',
            },
        ),
        migrations.AlterModelOptions(
            name='deliveryparcelmodel',
            options={'verbose_name': 'delivery order', 'verbose_name_plural': 'Delivery orders'},
        ),
        migrations.AlterModelOptions(
            name='deliverytariffmodel',
            options={'verbose_name': 'delivery tariff', 'verbose_name_plural': 'Tariff: Delivery'},
        ),
    ]
