# Generated by Django 3.2.13 on 2022-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0022_auto_20220620_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couriertariffmodel',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
