# Generated by Django 3.2.13 on 2022-06-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0023_alter_couriertariffmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='courier',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='crm_employees.couriertariffmodel'),
            preserve_default=False,
        ),
    ]
