# Generated by Django 3.2.13 on 2022-06-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0024_deliveryparcelmodel_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryparcelmodel',
            name='courier',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='crm_employees.couriertariffmodel'),
        ),
    ]
