# Generated by Django 3.2.13 on 2022-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0025_alter_deliveryparcelmodel_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryparcelmodel',
            name='ordering_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
