# Generated by Django 3.2.13 on 2022-06-20 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0026_alter_deliveryparcelmodel_ordering_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'discount value',
                'verbose_name_plural': 'Tariff: Discount',
            },
        ),
    ]
