# Generated by Django 3.2.13 on 2022-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0028_deliveryparcelmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='invoice',
            field=models.ImageField(blank=True, upload_to='media/images/invoices'),
        ),
        migrations.AddField(
            model_name='deliveryparcelmodel',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='media/images/receipts'),
        ),
    ]
