# Generated by Django 3.2.13 on 2022-06-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_employees', '0003_auto_20220611_1846'),
        ('accounts', '0003_customerrecipientinfomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRecipientInfoModel',
        ),
    ]
