# Generated by Django 3.2.13 on 2022-06-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_customerrecipientinfomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_role',
        ),
    ]
