# Generated by Django 3.2.13 on 2022-06-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220613_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_position',
            field=models.CharField(choices=[('MEN', 'Manager'), ('CEO', 'Chief Executive Officer')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
