# Generated by Django 3.2.13 on 2022-06-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_position',
            field=models.CharField(choices=[('MEN', 'Manager'), ('CEO', 'Chief Executive Officer'), ('FOU', 'Founder')], max_length=3),
        ),
    ]
