# Generated by Django 3.2.13 on 2022-06-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220614_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_position_3',
            field=models.CharField(blank=True, choices=[('MEN', 'Manager'), ('CEO', 'Chief Executive Officer'), ('FOU', 'Founder')], max_length=3),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_position_2',
            field=models.CharField(blank=True, choices=[('MEN', 'Manager'), ('CEO', 'Chief Executive Officer'), ('FOU', 'Founder')], max_length=3),
        ),
    ]
