# Generated by Django 3.2.13 on 2022-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'menu tag',
                'verbose_name_plural': 'Menu tags',
            },
        ),
    ]
