# Generated by Django 3.2.13 on 2022-07-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220701_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='main_photo',
            new_name='image',
        ),
    ]
