# Generated by Django 3.2.13 on 2022-06-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExampleTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamplePreviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='media/portfolio/examples/pictures')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.portfolioexampletagmodel')),
            ],
            options={
                'verbose_name': 'example preview',
                'verbose_name_plural': 'Examples previews',
            },
        ),
    ]
