# Generated by Django 3.2.13 on 2022-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220618_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioExampleCategoryModel',
            new_name='ExampleCategoryModel',
        ),
    ]
