# Generated by Django 3.2.13 on 2022-06-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_portfolioexamplecategorymodel_examplecategorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplepreviewmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='examplecategorymodel',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portfolio.examplecategorymodel'),
            preserve_default=False,
        ),
    ]
