# Generated by Django 3.2.13 on 2022-06-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220618_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplecategorymodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='examplepreviewmodel',
            name='tag1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='example_category_tag_one', to='portfolio.examplepreviewmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examplepreviewmodel',
            name='tag2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='example_category_tag_two', to='portfolio.examplepreviewmodel'),
            preserve_default=False,
        ),
    ]
