# Generated by Django 3.2.13 on 2022-06-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220618_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepreviewmodel',
            name='tag1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='example_category_tag_one', to='portfolio.examplecategorymodel'),
        ),
        migrations.AlterField(
            model_name='examplepreviewmodel',
            name='tag2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='example_category_tag_two', to='portfolio.examplecategorymodel'),
        ),
        migrations.AlterField(
            model_name='examplepreviewmodel',
            name='tag3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='example_category_tag_three', to='portfolio.examplecategorymodel'),
        ),
    ]
