# Generated by Django 3.2.13 on 2022-06-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_examplepreviewmodel_tag2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepreviewmodel',
            name='tag3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='example_category_tag_three', to='portfolio.examplecategorymodel'),
        ),
    ]
