# Generated by Django 3.2.13 on 2022-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_examplepreviewmodel_tag3'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplepreviewmodel',
            name='example_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
