# Generated by Django 3.2.13 on 2022-06-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_examplepreviewmodel_example_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examplecategorymodel',
            old_name='tag',
            new_name='title',
        ),
    ]
