# Generated by Django 3.2.13 on 2022-06-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.TimeField()),
                ('description', models.TextField()),
                ('event_preview', models.ImageField(blank=True, default='default_image.png', upload_to='media/battle/images/event_preview/')),
                ('quote1', models.TextField(blank=True)),
                ('quote2', models.TextField(blank=True)),
                ('quote3', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='GeneralDayDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('day_title', models.CharField(max_length=200)),
                ('daily_image', models.ImageField(upload_to='media/battle/images/')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='ItemCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categores',
            },
        ),
        migrations.CreateModel(
            name='LostItemsListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=16)),
                ('tanks', models.CharField(max_length=16)),
                ('battle_armored_vehicle', models.CharField(max_length=16)),
                ('artilery_system', models.CharField(max_length=16)),
                ('rszo', models.CharField(max_length=16)),
                ('antyair_missle', models.CharField(max_length=16)),
                ('airplanes', models.CharField(max_length=16)),
                ('helicopters', models.CharField(max_length=16)),
                ('vehicles', models.CharField(max_length=16)),
                ('ships_and_boats', models.CharField(max_length=16)),
                ('bpla', models.CharField(max_length=16)),
                ('special_vehicle', models.CharField(max_length=16)),
                ('rockets', models.CharField(max_length=16)),
                ('date', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='battle.generaldaydescriptionmodel')),
            ],
            options={
                'verbose_name': 'or change items info',
                'verbose_name_plural': 'Lost items list',
            },
        ),
        migrations.CreateModel(
            name='DayVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(upload_to='media/battle/video/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.itemcategorymodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.generaldaydescriptionmodel')),
                ('parent_event_time', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='battle.dayeventmodel')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='DayPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('media', models.ImageField(upload_to='media/battle/photo/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photocategory', to='battle.itemcategorymodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.generaldaydescriptionmodel')),
                ('parent_event_time', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='battle.dayeventmodel')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.AddField(
            model_name='dayeventmodel',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.generaldaydescriptionmodel'),
        ),
        migrations.CreateModel(
            name='DayAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(upload_to='media/battle/audio/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.itemcategorymodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.generaldaydescriptionmodel')),
                ('parent_event_time', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='battle.dayeventmodel')),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'Audios',
            },
        ),
        migrations.CreateModel(
            name='DayArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('article', models.FileField(upload_to='media/battle/video/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.itemcategorymodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle.generaldaydescriptionmodel')),
                ('parent_event_time', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='battle.dayeventmodel')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
